- defaults:
    link:
      create: true
      relink: true
- shell:
  -
    - git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
    - Install Tmux Plugin Manager
- link:
    ~/.tmux.conf: apps/tmux/tmux.conf
