- defaults:
    link:
      create: true
      relink: true
- shell:
  - 
    - git clone https://github.com/gpakosz/.tmux.git ~/.tmux
    - Clone gpakosz/.tmux.git
  # -
  #   - git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
  #   - Install Tmux Plugin Manager
- link: 
    ~/.tmux.conf: ~/.tmux/.tmux.conf
    ~/.tmux.conf.local: apps/tmux/tmux.conf.local
